level = [  #Defining the boundaries and walls 
"WWWWWWWWWWWWWWWWWWWWWWWWW",
"W                       W",
"W            W          W",
"W            W          W",
"W                       W",
"W             W         W",
"W             W         W",
"W                       W",
"WWWWWW                  W",
"W                       W",
"W                       W",
"W        W              W",
"W        W              W",
"W        W              W",
"W        W              W",
"W                       W",
"W               W       W",
"W               W       W",
"W                       W",
"W                       W",
"W                       W",
"W     WWWWWW            W",
"W          W            W",
"W                       W",
"WWWWWWWWWWWWWWWWWWWWWWWWW",
]